SERVER_ID = '1066b629bebc4c3d9f236c33c013e084'
VERSION_SIZE = 1
MESSAGE_SIZE_SIZE = 4
SERVER_HEADER_SIZE = 7
NONCE_SIZE = 8
EXPIRATION_TIME_SIZE = CREATION_TIME_SIZE = 8
CLIENT_ID_SIZE = SERVER_ID_SIZE = 16
AES_CBC_BLOCK_SIZE = 16
ENCRYPTED_KEY_IV_SIZE = TICKET_IV_SIZE = AUTHENTICATOR_IV_SIZE = MESSAGE_IV_SIZE = 16
CLIENT_VERSION = 24
AES_KEY_SIZE = 32
DECRYPTED_TICKET_SIZE = 121
CLIENT_NAME_SIZE = CLIENT_PASSWORD_SIZE = 255
NAME_SIZE = PASSWORD_SIZE = 255
PACKET_SIZE = 1024
AUTHENTICATOR_SIZE = AUTHENTICATOR_IV_SIZE + VERSION_SIZE + CLIENT_ID_SIZE + SERVER_ID_SIZE + CREATION_TIME_SIZE
TICKET_SIZE = (VERSION_SIZE + CLIENT_ID_SIZE + SERVER_ID_SIZE + CREATION_TIME_SIZE + TICKET_IV_SIZE + AES_KEY_SIZE +
               EXPIRATION_TIME_SIZE)
