import base64

SERVERS_MUTUAL_KEY = base64.b64decode(b'DlU/1WUMQgbfqzX+mO5QlNzUAQT7VpJUE1vfHouFO/s=')
VERSION_SIZE = 1
MESSAGE_SIZE_SIZE = 4
CREATION_TIME_SIZE = EXPIRATION_TIME_SIZE = 8
AUTHENTICATOR_IV_SIZE = TICKET_IV_SIZE = MESSAGE_IV_SIZE = 16
CLIENT_ID_SIZE = SERVER_ID_SIZE = 16
AES_CBC_BLOCK_SIZE = 16
SERVER_VERSION = 24
AES_KEY_SIZE = 32
PACKET_SIZE = 1024
AUTHENTICATOR_SIZE = AUTHENTICATOR_IV_SIZE + VERSION_SIZE + CLIENT_ID_SIZE + SERVER_ID_SIZE + CREATION_TIME_SIZE
TICKET_SIZE = (VERSION_SIZE + CLIENT_ID_SIZE + SERVER_ID_SIZE + CREATION_TIME_SIZE + TICKET_IV_SIZE + AES_KEY_SIZE +
               EXPIRATION_TIME_SIZE)
