import base64
from servers_mutual_key import get_key_from_file

CLIENT_FILE_PATH = './clients.txt'
SERVERS_MUTUAL_KEY = base64.b64decode(get_key_from_file())

VERSION_SIZE = 1
NONCE_SIZE = 8
EXPIRATION_TIME_SIZE = CREATION_TIME_SIZE = 8
CLIENT_ID_SIZE = 16
SERVER_ID_SIZE = 16
ENCRYPTED_KEY_IV_SIZE = TICKET_IV_SIZE = 16
AES_CBC_BLOCK_SIZE = 16
SERVER_VERSION = 24
AES_KEY_SIZE = 32
CLIENT_NAME_SIZE = 255
CLIENT_PASSWORD_SIZE = 255
PACKET_SIZE = 1024
ENCRYPTED_KEY_SIZE = ENCRYPTED_KEY_IV_SIZE + NONCE_SIZE + AES_KEY_SIZE
TICKET_SIZE = (VERSION_SIZE + CLIENT_ID_SIZE + SERVER_ID_SIZE + CREATION_TIME_SIZE + TICKET_IV_SIZE + AES_KEY_SIZE +
               EXPIRATION_TIME_SIZE)
